migrate:
	poetry run python manage.py migrate

migrations:
	poetry run python manage.py migrations

runserver:
	poetry run python manage.py runserver

superuser:
	poetry run python manage.py createsuperuser